export const HOBBIES_PICKED_SET = 'setPickedHobbies'
export const HOBBIES_OPTIONAL_SET = 'setOptionalHobbies'
export const HOBBY_ADD = 'hobbyAddNew'
export const HOBBY_UPDATE_BY_UUID = 'hobbyUpdate'
export const HOBBY_DROP = 'hobbyDrop'
